services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mygemini_zero_v2
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
      - ./vector_store:/app/vector_store
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
